name: mom6_diags # Remember conda environments are not case sensitive

channels:
  - conda-forge
  - nodefaults

dependencies: # just coppied from cupid_analysis in hopes of preserving compatibility
  - cartopy
  - cftime
  - dask
  - distributed
  - geocat-comp
  - geopandas
  - intake
  - intake-esm
  - intake-xarray
  - ipykernel
  - matplotlib
  - nc-time-axis
  - ncar-jobqueue
  - netcdf4
  - numpy
  - pip
  - python==3.11.4
  - uxarray
  - xarray
  - xesmf
  - yaml
  - zarr
  - pip:
    - -e ./ # mom6_diags package